sudo: required
services:
  - docker

before_install:
  - docker build -t hoyhung/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hoyhung/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-954487248195"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    SECURE: "$AWS_SECRET_KEY"

language: generic
